import { PDFDocument, StandardFonts, rgb } from "pdf-lib";


export interface ReceiptPdfLineItem {
  description: string;
  quantity?: number | null;
  unit_price?: number | null;
  total: number;
}

export type PdfLang = "da" | "en";

export interface ReceiptPdfData {
  company: string;
  amount: number;
  currency: string;
  date: string;
  due_date?: string | null;
  document_type: "receipt" | "invoice";
  category?: string | null;
  notes?: string | null;
  items?: ReceiptPdfLineItem[];
  receipt_id: string;
  /** Raw PNG/JPEG bytes for the vendor logo. If omitted, a monogram is rendered. */
  vendor_logo?: Uint8Array | null;
  lang?: PdfLang;
}

const L = {
  da: {
    tagline: "Digital kvittering",
    receipt: "KVITTERING",
    invoice: "FAKTURA",
    billedBy: "Udstedt af",
    dateIssued: "Udstedelsesdato",
    dueDate: "Betalingsfrist",
    category: "Kategori",
    uncategorized: "Ukategoriseret",
    documentId: "Dokument-ID",
    totalAmount: "Total",
    items: "Varer",
    description: "Beskrivelse",
    qty: "Antal",
    unit: "Enhedspris",
    total: "Total",
    subtotal: "Subtotal",
    discount: "Rabat",
    deposit: "Pant",
    vat: "Moms",
    notes: "Bemærkninger",
    footer: "Genereret af Kvitregn - din digitale kvitteringsmappe.",
  },
  en: {
    tagline: "Digital receipt",
    receipt: "RECEIPT",
    invoice: "INVOICE",
    billedBy: "Billed by",
    dateIssued: "Date issued",
    dueDate: "Due date",
    category: "Category",
    uncategorized: "Uncategorized",
    documentId: "Document ID",
    totalAmount: "Total amount",
    items: "Items",
    description: "Description",
    qty: "Qty",
    unit: "Unit",
    total: "Total",
    subtotal: "Subtotal",
    discount: "Discount",
    deposit: "Deposit",
    vat: "VAT",
    notes: "Notes",
    footer: "Generated by Kvitregn - your receipts and invoices wallet.",
  },
} as const;

// pdf-lib StandardFonts (WinAnsi) can't encode some non-Latin1 characters
// (e.g. em-dash, curly quotes). Sanitize to safe ASCII-ish equivalents.
function sanitize(s: string): string {
  return s
    .replace(/[\u2014\u2013]/g, "-")
    .replace(/[\u2018\u2019]/g, "'")
    .replace(/[\u201C\u201D]/g, '"')
    .replace(/\u2026/g, "...");
}

function fmtMoney(amount: number, currency: string, lang: PdfLang) {
  try {
    return new Intl.NumberFormat(lang === "da" ? "da-DK" : "en-GB", {
      style: "currency",
      currency,
    }).format(amount);
  } catch {
    return `${amount.toFixed(2)} ${currency}`;
  }
}

// Brand palette
const INK = rgb(0x23 / 255, 0x24 / 255, 0x1f / 255); // #23241f
const DUSTY = rgb(0x6b / 255, 0x93 / 255, 0xa8 / 255); // #6b93a8
const CREAM = rgb(0xf5 / 255, 0xf2 / 255, 0xea / 255); // #f5f2ea
const MUTED = rgb(0.42, 0.45, 0.5);
const LINE = rgb(0.85, 0.83, 0.78);

export async function generateReceiptPdf(data: ReceiptPdfData): Promise<Uint8Array> {
  const lang: PdfLang = data.lang === "en" ? "en" : "da";
  const t = L[lang];

  const doc = await PDFDocument.create();
  const page = doc.addPage([595.28, 841.89]);
  const { width, height } = page.getSize();
  const font = await doc.embedFont(StandardFonts.Helvetica);
  const bold = await doc.embedFont(StandardFonts.HelveticaBold);
  const italic = await doc.embedFont(StandardFonts.HelveticaOblique);
  const draw = (text: string, opts: Parameters<typeof page.drawText>[1]) =>
    page.drawText(sanitize(text), opts);

  // Header band (cream)
  page.drawRectangle({ x: 0, y: height - 120, width, height: 120, color: CREAM });

  // Brand wordmark - typographic "Kvitregn"
  draw("Kvitregn", { x: 48, y: height - 60, size: 26, font: bold, color: INK });
  // Small accent dot
  page.drawCircle({ x: 48 + bold.widthOfTextAtSize("Kvitregn", 26) + 6, y: height - 55, size: 3, color: DUSTY });
  draw(t.tagline, { x: 48, y: height - 82, size: 10, font: italic, color: DUSTY });

  const label = data.document_type === "invoice" ? t.invoice : t.receipt;
  const labelWidth = bold.widthOfTextAtSize(sanitize(label), 12);
  draw(label, { x: width - 48 - labelWidth, y: height - 55, size: 12, font: bold, color: INK });
  const idText = `#${data.receipt_id.slice(0, 8).toUpperCase()}`;
  const idWidth = font.widthOfTextAtSize(idText, 10);
  draw(idText, { x: width - 48 - idWidth, y: height - 78, size: 10, font, color: MUTED });

  // Divider under header
  page.drawLine({
    start: { x: 0, y: height - 120 },
    end: { x: width, y: height - 120 },
    thickness: 1,
    color: DUSTY,
  });

  let y = height - 160;
  draw(t.billedBy, { x: 48, y, size: 9, font, color: MUTED });
  y -= 18;

  // Vendor row: logo (or monogram) + name
  const AVATAR_SIZE = 36;
  const avatarX = 48;
  const avatarY = y - AVATAR_SIZE + 20; // baseline align roughly with 20pt text
  await drawVendorMark(doc, page, data.company, data.vendor_logo ?? null, avatarX, avatarY, AVATAR_SIZE, bold);
  draw(data.company || "-", { x: avatarX + AVATAR_SIZE + 12, y, size: 20, font: bold, color: INK });

  y -= 44;
  const rows: Array<[string, string]> = [
    [t.dateIssued, data.date || "-"],
    ...(data.due_date ? ([[t.dueDate, data.due_date]] as Array<[string, string]>) : []),
    [t.category, data.category || t.uncategorized],
    [t.documentId, data.receipt_id],
  ];
  for (const [k, v] of rows) {
    draw(k, { x: 48, y, size: 9, font, color: MUTED });
    draw(v, { x: 200, y, size: 11, font, color: INK });
    y -= 22;
  }

  y -= 6;
  page.drawLine({ start: { x: 48, y }, end: { x: width - 48, y }, thickness: 1, color: LINE });

  // Items table
  const items = data.items ?? [];
  const currency = data.currency || "DKK";
  y -= 30;

  if (items.length > 0) {
    // Column x positions (right-aligned for numeric columns)
    const xDesc = 48;
    const xQty = width - 260;
    const xUnit = width - 190;
    const xTotal = width - 48;

    draw(t.items, { x: xDesc, y, size: 9, font, color: MUTED });
    y -= 18;

    // Header row
    draw(t.description, { x: xDesc, y, size: 9, font: bold, color: INK });
    const qtyW = bold.widthOfTextAtSize(sanitize(t.qty), 9);
    draw(t.qty, { x: xQty - qtyW / 2, y, size: 9, font: bold, color: INK });
    const unitW = bold.widthOfTextAtSize(sanitize(t.unit), 9);
    draw(t.unit, { x: xUnit + 40 - unitW, y, size: 9, font: bold, color: INK });
    const totW = bold.widthOfTextAtSize(sanitize(t.total), 9);
    draw(t.total, { x: xTotal - totW, y, size: 9, font: bold, color: INK });
    y -= 6;
    page.drawLine({ start: { x: 48, y }, end: { x: width - 48, y }, thickness: 0.6, color: LINE });
    y -= 14;

    const descMaxW = xQty - xDesc - 20;
    let subtotal = 0;
    for (const it of items) {
      if (y < 200) break;
      const isNeg = it.total < 0;
      let desc = sanitize(it.description || "");
      while (font.widthOfTextAtSize(desc, 10) > descMaxW && desc.length > 3) desc = desc.slice(0, -2);
      draw(desc, { x: xDesc, y, size: 10, font, color: isNeg ? DUSTY : INK });
      if (it.quantity != null) {
        const q = String(it.quantity).replace(".", ",");
        const qw = font.widthOfTextAtSize(q, 10);
        draw(q, { x: xQty - qw / 2, y, size: 10, font, color: INK });
      }
      if (it.unit_price != null) {
        const up = fmtMoney(it.unit_price, currency, lang);
        const upw = font.widthOfTextAtSize(sanitize(up), 10);
        draw(up, { x: xUnit + 40 - upw, y, size: 10, font, color: INK });
      }
      const totalText = fmtMoney(it.total, currency, lang);
      const tW = font.widthOfTextAtSize(sanitize(totalText), 10);
      draw(totalText, { x: xTotal - tW, y, size: 10, font, color: isNeg ? DUSTY : INK });
      subtotal += it.total;
      y -= 16;
    }

    y -= 6;
    page.drawLine({ start: { x: xQty - 40, y }, end: { x: width - 48, y }, thickness: 0.6, color: LINE });
    y -= 14;

    // Subtotal
    if (Math.abs(subtotal - data.amount) > 0.01) {
      const label = t.subtotal;
      const sw = font.widthOfTextAtSize(sanitize(label), 10);
      draw(label, { x: xTotal - 180 - sw, y, size: 10, font, color: MUTED });
      const sub = fmtMoney(subtotal, currency, lang);
      const subW = font.widthOfTextAtSize(sanitize(sub), 10);
      draw(sub, { x: xTotal - subW, y, size: 10, font, color: INK });
      y -= 16;
    }
  }

  // Total card
  y -= 10;
  page.drawRectangle({
    x: 48,
    y: y - 60,
    width: width - 96,
    height: 78,
    color: CREAM,
    borderColor: DUSTY,
    borderWidth: 1,
  });
  draw(t.totalAmount, { x: 68, y: y + 2, size: 10, font, color: MUTED });
  const totalStr = fmtMoney(data.amount || 0, currency, lang);
  draw(totalStr, { x: 68, y: y - 32, size: 26, font: bold, color: INK });

  y -= 90;

  if (data.notes) {
    if (y < 140) y = 140;
    draw(t.notes, { x: 48, y, size: 9, font, color: MUTED });
    y -= 16;
    const words = sanitize(data.notes).split(/\s+/);
    let curLine = "";
    const maxW = width - 96;
    for (const w of words) {
      const test = curLine ? `${curLine} ${w}` : w;
      if (font.widthOfTextAtSize(test, 10) > maxW) {
        draw(curLine, { x: 48, y, size: 10, font, color: INK });
        y -= 14;
        curLine = w;
      } else curLine = test;
    }
    if (curLine) draw(curLine, { x: 48, y, size: 10, font, color: INK });
  }

  // Footer
  page.drawLine({ start: { x: 48, y: 80 }, end: { x: width - 48, y: 80 }, thickness: 1, color: LINE });
  draw(t.footer, { x: 48, y: 60, size: 9, font: italic, color: DUSTY });
  draw(new Date().toISOString().slice(0, 10), { x: 48, y: 46, size: 9, font, color: MUTED });

  return await doc.save();
}
