import { PDFDocument, StandardFonts, rgb } from "pdf-lib";

export interface ReceiptPdfLineItem {
  description: string;
  quantity?: number | null;
  unit_price?: number | null;
  total: number;
}

export type PdfLang = "da" | "en";

export interface ReceiptPdfData {
  company: string;
  amount: number;
  currency: string;
  date: string;
  due_date?: string | null;
  document_type: "receipt" | "invoice";
  category?: string | null;
  notes?: string | null;
  items?: ReceiptPdfLineItem[];
  receipt_id: string;
  /** Kept for API compatibility; no longer rendered (no avatar on financial documents). */
  vendor_logo?: Uint8Array | null;
  /** Business profile of the user, rendered as an "Afsender" block. */
  sender?: {
    company_name: string;
    cvr?: string | null;
    address?: string | null;
    postal_code?: string | null;
    city?: string | null;
    phone?: string | null;
    email?: string | null;
  } | null;
  lang?: PdfLang;
}

const L = {
  da: {
    tagline: "Digital kvitteringsmappe",
    receipt: "KVITTERING",
    invoice: "FAKTURA",
    billedBy: "Udstedt af",
    sender: "Afsender",
    cvr: "CVR-nr.",
    phone: "Tlf.",
    email: "Email",
    dateIssued: "Udstedelsesdato",
    dueDate: "Forfaldsdato",
    category: "Kategori",
    uncategorized: "Ukategoriseret",
    documentId: "Dokument-ID",
    number: "Nr.",
    description: "Beskrivelse",
    qty: "Antal",
    unit: "Enhedspris",
    total: "Beløb",
    exVat: "Beløb ekskl. moms",
    vat: "Moms 25%",
    grandTotal: "I ALT INKL. MOMS",
    notes: "Bemærkninger",
    generated: "Genereret",
    footer: "Genereret af Kvitregn - din digitale kvitteringsmappe.",
  },
  en: {
    tagline: "Digital receipts wallet",
    receipt: "RECEIPT",
    invoice: "INVOICE",
    billedBy: "Billed by",
    sender: "From",
    cvr: "CVR",
    phone: "Phone",
    email: "Email",
    dateIssued: "Date issued",
    dueDate: "Due date",
    category: "Category",
    uncategorized: "Uncategorized",
    documentId: "Document ID",
    number: "No.",
    description: "Description",
    qty: "Qty",
    unit: "Unit price",
    total: "Amount",
    exVat: "Amount excl. VAT",
    vat: "VAT 25%",
    grandTotal: "TOTAL INCL. VAT",
    notes: "Notes",
    generated: "Generated",
    footer: "Generated by Kvitregn - your receipts and invoices wallet.",
  },
} as const;

function sanitize(s: string): string {
  return s
    .replace(/[\u2014\u2013]/g, "-")
    .replace(/[\u2018\u2019]/g, "'")
    .replace(/[\u201C\u201D]/g, '"')
    .replace(/\u2026/g, "...");
}

function fmtMoney(amount: number, currency: string, lang: PdfLang) {
  try {
    return new Intl.NumberFormat(lang === "da" ? "da-DK" : "en-GB", {
      style: "currency",
      currency,
    }).format(amount);
  } catch {
    return `${amount.toFixed(2)} ${currency}`;
  }
}

function fmtDate(iso: string | null | undefined, lang: PdfLang): string {
  if (!iso) return "-";
  const m = /^(\d{4})-(\d{2})-(\d{2})/.exec(iso);
  if (!m) return iso;
  const [, y, mo, d] = m;
  return lang === "da" ? `${d}.${mo}.${y}` : `${d}/${mo}/${y}`;
}

// Neutral, print-safe palette with a single brand accent.
const INK = rgb(0x23 / 255, 0x24 / 255, 0x1f / 255);
const ACCENT = rgb(0x6b / 255, 0x93 / 255, 0xa8 / 255);
const MUTED = rgb(0.42, 0.45, 0.5);
const LINE = rgb(0.84, 0.84, 0.82);
const SOFT = rgb(0.96, 0.96, 0.95);

const MARGIN = 52;
const BODY = 9.5;
const HEAD = 11;

export async function generateReceiptPdf(data: ReceiptPdfData): Promise<Uint8Array> {
  const lang: PdfLang = data.lang === "en" ? "en" : "da";
  const t = L[lang];

  const doc = await PDFDocument.create();
  const page = doc.addPage([595.28, 841.89]);
  const { width, height } = page.getSize();
  const font = await doc.embedFont(StandardFonts.Helvetica);
  const bold = await doc.embedFont(StandardFonts.HelveticaBold);

  const draw = (text: string, opts: Parameters<typeof page.drawText>[1]) =>
    page.drawText(sanitize(text), opts);
  const w = (text: string, size: number, f = font) => f.widthOfTextAtSize(sanitize(text), size);
  const drawRight = (
    text: string,
    x: number,
    y: number,
    size: number,
    f = font,
    color = INK,
  ) => draw(text, { x: x - w(text, size, f), y, size, font: f, color });

  const right = width - MARGIN;
  const currency = data.currency || "DKK";

  // ---------- Masthead ----------
  let y = height - MARGIN;
  draw("Kvitregn", { x: MARGIN, y: y - 12, size: 14, font: bold, color: INK });
  page.drawCircle({ x: MARGIN + w("Kvitregn", 14, bold) + 4, y: y - 8, size: 2, color: ACCENT });
  draw(t.tagline, { x: MARGIN, y: y - 26, size: 8, font, color: MUTED });

  const title = data.document_type === "invoice" ? t.invoice : t.receipt;
  drawRight(title, right, y - 14, 20, bold, INK);
  drawRight(
    `${t.number} ${data.receipt_id.slice(0, 8).toUpperCase()}`,
    right,
    y - 30,
    BODY,
    font,
    MUTED,
  );

  y -= 46;
  page.drawLine({
    start: { x: MARGIN, y },
    end: { x: right, y },
    thickness: 1,
    color: ACCENT,
  });

  // ---------- Parties ----------
  y -= 26;
  const partyTop = y;
  const colRightX = MARGIN + (right - MARGIN) / 2 + 10;

  // Left: supplier ("Udstedt af")
  draw(t.billedBy, { x: MARGIN, y: partyTop, size: 8, font, color: MUTED });
  let ly = partyTop - 16;
  draw(data.company || "-", { x: MARGIN, y: ly, size: HEAD, font: bold, color: INK });
  ly -= 14;

  // Right: own company ("Afsender")
  let ry = partyTop;
  if (data.sender) {
    const s = data.sender;
    draw(t.sender, { x: colRightX, y: ry, size: 8, font, color: MUTED });
    ry -= 16;
    const lines: Array<[string, boolean]> = [
      [s.company_name, true],
      [s.address ?? "", false],
      [[s.postal_code ?? "", s.city ?? ""].filter(Boolean).join(" "), false],
      [s.cvr ? `${t.cvr} ${s.cvr}` : "", false],
      [s.phone ? `${t.phone} ${s.phone}` : "", false],
      [s.email ?? "", false],
    ];
    for (const [line, isName] of lines) {
      if (!line.trim()) continue;
      draw(line, {
        x: colRightX,
        y: ry,
        size: isName ? HEAD : BODY,
        font: isName ? bold : font,
        color: isName ? INK : MUTED,
      });
      ry -= isName ? 15 : 12;
    }
  }

  // ---------- Meta row ----------
  y = Math.min(ly, ry) - 14;
  const meta: Array<[string, string]> = [
    [t.dateIssued, fmtDate(data.date, lang)],
    ...(data.due_date
      ? ([] as Array<[string, string]>) // shown in the highlighted callout near the total
      : []),
    [t.category, data.category || t.uncategorized],
  ];
  page.drawLine({ start: { x: MARGIN, y: y + 10 }, end: { x: right, y: y + 10 }, thickness: 0.5, color: LINE });
  let mx = MARGIN;
  const metaW = (right - MARGIN) / meta.length;
  for (const [k, v] of meta) {
    draw(k, { x: mx, y: y - 6, size: 8, font, color: MUTED });
    draw(v, { x: mx, y: y - 20, size: BODY, font: bold, color: INK });
    mx += metaW;
  }
  y -= 38;
  page.drawLine({ start: { x: MARGIN, y }, end: { x: right, y }, thickness: 0.5, color: LINE });

  // ---------- Items table ----------
  const items = data.items ?? [];
  y -= 26;

  const xDesc = MARGIN;
  const xQty = right - 250;
  const xUnit = right - 130;
  const xTotal = right;
  let subtotal = 0;

  if (items.length > 0) {
    draw(t.description, { x: xDesc, y, size: 8, font: bold, color: MUTED });
    drawRight(t.qty, xQty, y, 8, bold, MUTED);
    drawRight(t.unit, xUnit, y, 8, bold, MUTED);
    drawRight(t.total, xTotal, y, 8, bold, MUTED);
    y -= 8;
    page.drawLine({ start: { x: MARGIN, y }, end: { x: right, y }, thickness: 0.8, color: INK });
    y -= 16;

    const descMaxW = xQty - xDesc - 24;
    for (const it of items) {
      if (y < 250) break;
      let desc = sanitize(it.description || "");
      while (font.widthOfTextAtSize(desc, BODY) > descMaxW && desc.length > 3)
        desc = desc.slice(0, -2);
      draw(desc, { x: xDesc, y, size: BODY, font, color: INK });
      if (it.quantity != null) drawRight(String(it.quantity).replace(".", ","), xQty, y, BODY);
      if (it.unit_price != null)
        drawRight(fmtMoney(it.unit_price, currency, lang), xUnit, y, BODY);
      drawRight(fmtMoney(it.total, currency, lang), xTotal, y, BODY, font, INK);
      subtotal += it.total;
      y -= 9;
      page.drawLine({ start: { x: MARGIN, y }, end: { x: right, y }, thickness: 0.4, color: LINE });
      y -= 15;
    }
    y -= 6;
  }

  // ---------- Totals ----------
  const gross = data.amount || 0;
  const exVat = gross / 1.25;
  const vat = gross - exVat;

  const boxW = 250;
  const boxX = right - boxW;
  const rowsH = 3 * 16 + 34;
  const boxY = y - rowsH;

  let ty = y - 14;
  drawRight(t.exVat, boxX + 150, ty, BODY, font, MUTED);
  drawRight(fmtMoney(exVat, currency, lang), right, ty, BODY, font, INK);
  ty -= 16;
  drawRight(t.vat, boxX + 150, ty, BODY, font, MUTED);
  drawRight(fmtMoney(vat, currency, lang), right, ty, BODY, font, INK);
  ty -= 12;
  page.drawLine({ start: { x: boxX, y: ty }, end: { x: right, y: ty }, thickness: 0.8, color: INK });
  ty -= 22;
  page.drawRectangle({ x: boxX, y: ty - 8, width: boxW, height: 28, color: SOFT });
  draw(t.grandTotal, { x: boxX + 8, y: ty, size: 9, font: bold, color: INK });
  drawRight(fmtMoney(gross, currency, lang), right - 8, ty - 1, 13, bold, INK);

  // Forfaldsdato highlighted, left of the totals
  if (data.due_date) {
    const dY = y - 30;
    page.drawRectangle({
      x: MARGIN,
      y: dY - 12,
      width: 190,
      height: 44,
      borderColor: ACCENT,
      borderWidth: 1,
    });
    draw(t.dueDate, { x: MARGIN + 10, y: dY + 16, size: 8, font, color: MUTED });
    draw(fmtDate(data.due_date, lang), {
      x: MARGIN + 10,
      y: dY,
      size: 13,
      font: bold,
      color: INK,
    });
  }

  y = Math.min(boxY, ty - 30);

  // ---------- Notes ----------
  if (data.notes && y > 150) {
    draw(t.notes, { x: MARGIN, y, size: 8, font, color: MUTED });
    y -= 14;
    const words = sanitize(data.notes).split(/\s+/);
    let cur = "";
    const maxW = right - MARGIN;
    for (const word of words) {
      const test = cur ? `${cur} ${word}` : word;
      if (font.widthOfTextAtSize(test, BODY) > maxW) {
        draw(cur, { x: MARGIN, y, size: BODY, font, color: INK });
        y -= 13;
        cur = word;
        if (y < 120) break;
      } else cur = test;
    }
    if (cur && y > 110) draw(cur, { x: MARGIN, y, size: BODY, font, color: INK });
  }

  // ---------- Footer ----------
  page.drawLine({
    start: { x: MARGIN, y: 78 },
    end: { x: right, y: 78 },
    thickness: 0.5,
    color: LINE,
  });
  draw(`${t.documentId}: ${data.receipt_id}`, { x: MARGIN, y: 62, size: 7.5, font, color: MUTED });
  draw(`${t.generated}: ${new Date().toISOString().slice(0, 10)}`, {
    x: MARGIN,
    y: 50,
    size: 7.5,
    font,
    color: MUTED,
  });
  drawRight(t.footer, right, 50, 7.5, font, MUTED);

  return await doc.save();
}
