import { PDFDocument, StandardFonts, rgb } from "pdf-lib";

export interface ReceiptPdfLineItem {
  description: string;
  quantity?: number | null;
  unit_price?: number | null;
  total: number;
}

export type PdfLang = "da" | "en";

export interface ReceiptPdfData {
  company: string;
  amount: number;
  currency: string;
  date: string;
  due_date?: string | null;
  document_type: "receipt" | "invoice";
  category?: string | null;
  notes?: string | null;
  items?: ReceiptPdfLineItem[];
  receipt_id: string;
  lang?: PdfLang;
}

const L = {
  da: {
    tagline: "Digital kvittering",
    receipt: "KVITTERING",
    invoice: "FAKTURA",
    billedBy: "Udstedt af",
    dateIssued: "Udstedelsesdato",
    dueDate: "Betalingsfrist",
    category: "Kategori",
    uncategorized: "Ukategoriseret",
    documentId: "Dokument-ID",
    totalAmount: "Total",
    items: "Varer",
    description: "Beskrivelse",
    qty: "Antal",
    unit: "Enhed",
    total: "Total",
    notes: "Bemærkninger",
    footer: "Genereret af Kvittr — din digitale kvitteringsmappe.",
  },
  en: {
    tagline: "Digital receipt",
    receipt: "RECEIPT",
    invoice: "INVOICE",
    billedBy: "Billed by",
    dateIssued: "Date issued",
    dueDate: "Due date",
    category: "Category",
    uncategorized: "Uncategorized",
    documentId: "Document ID",
    totalAmount: "Total amount",
    items: "Items",
    description: "Description",
    qty: "Qty",
    unit: "Unit",
    total: "Total",
    notes: "Notes",
    footer: "Generated by Kvittr — your receipts and invoices wallet.",
  },
} as const;

// pdf-lib StandardFonts (WinAnsi) can't encode some non-Latin1 characters
// (e.g. em-dash, curly quotes). Sanitize to safe ASCII-ish equivalents.
function sanitize(s: string): string {
  return s
    .replace(/[\u2014\u2013]/g, "-")
    .replace(/[\u2018\u2019]/g, "'")
    .replace(/[\u201C\u201D]/g, '"')
    .replace(/\u2026/g, "...");
}

function fmtMoney(amount: number, currency: string, lang: PdfLang) {
  try {
    return new Intl.NumberFormat(lang === "da" ? "da-DK" : "en-GB", { style: "currency", currency }).format(amount);
  } catch {
    return `${amount.toFixed(2)} ${currency}`;
  }
}

export async function generateReceiptPdf(data: ReceiptPdfData): Promise<Uint8Array> {
  const lang: PdfLang = data.lang === "en" ? "en" : "da";
  const t = L[lang];

  const doc = await PDFDocument.create();
  const page = doc.addPage([595.28, 841.89]);
  const { width, height } = page.getSize();
  const font = await doc.embedFont(StandardFonts.Helvetica);
  const bold = await doc.embedFont(StandardFonts.HelveticaBold);
  const draw = (text: string, opts: Parameters<typeof page.drawText>[1]) =>
    page.drawText(sanitize(text), opts);

  const ink = rgb(0.09, 0.11, 0.16);
  const muted = rgb(0.42, 0.45, 0.55);
  const line = rgb(0.88, 0.9, 0.94);
  const accent = rgb(0.36, 0.55, 0.98);

  page.drawRectangle({ x: 0, y: height - 110, width, height: 110, color: rgb(0.97, 0.98, 1) });
  draw("KVITTR", { x: 48, y: height - 55, size: 22, font: bold, color: accent });
  draw(t.tagline, { x: 48, y: height - 78, size: 10, font, color: muted });

  const label = data.document_type === "invoice" ? t.invoice : t.receipt;
  const labelWidth = bold.widthOfTextAtSize(sanitize(label), 12);
  draw(label, { x: width - 48 - labelWidth, y: height - 55, size: 12, font: bold, color: ink });
  const idText = `#${data.receipt_id.slice(0, 8).toUpperCase()}`;
  const idWidth = font.widthOfTextAtSize(idText, 10);
  draw(idText, { x: width - 48 - idWidth, y: height - 78, size: 10, font, color: muted });

  let y = height - 160;
  draw(t.billedBy, { x: 48, y, size: 9, font, color: muted });
  y -= 18;
  draw(data.company || "Unknown", { x: 48, y, size: 20, font: bold, color: ink });

  y -= 44;
  const rows: Array<[string, string]> = [
    [t.dateIssued, data.date || "-"],
    ...(data.due_date ? ([[t.dueDate, data.due_date]] as Array<[string, string]>) : []),
    [t.category, data.category || t.uncategorized],
    [t.documentId, data.receipt_id],
  ];
  for (const [k, v] of rows) {
    draw(k, { x: 48, y, size: 9, font, color: muted });
    draw(v, { x: 200, y, size: 11, font, color: ink });
    y -= 22;
  }

  y -= 6;
  page.drawLine({ start: { x: 48, y }, end: { x: width - 48, y }, thickness: 1, color: line });

  y -= 40;
  page.drawRectangle({
    x: 48, y: y - 60, width: width - 96, height: 90,
    color: rgb(0.97, 0.98, 1), borderColor: line, borderWidth: 1,
  });
  draw(t.totalAmount, { x: 68, y: y + 8, size: 10, font, color: muted });
  draw(fmtMoney(data.amount || 0, data.currency || "DKK", lang), {
    x: 68, y: y - 30, size: 30, font: bold, color: ink,
  });

  y -= 100;
  const items = data.items ?? [];
  if (items.length > 0) {
    draw(t.items, { x: 48, y, size: 9, font, color: muted });
    y -= 18;
    draw(t.description, { x: 48, y, size: 9, font: bold, color: ink });
    draw(t.qty, { x: width - 240, y, size: 9, font: bold, color: ink });
    draw(t.unit, { x: width - 190, y, size: 9, font: bold, color: ink });
    const totalHeaderW = bold.widthOfTextAtSize(sanitize(t.total), 9);
    draw(t.total, { x: width - 48 - totalHeaderW, y, size: 9, font: bold, color: ink });
    y -= 8;
    page.drawLine({ start: { x: 48, y }, end: { x: width - 48, y }, thickness: 0.5, color: line });
    y -= 14;

    const descMaxW = width - 48 - 260;
    for (const it of items) {
      if (y < 120) break;
      let desc = sanitize(it.description || "");
      while (font.widthOfTextAtSize(desc, 10) > descMaxW && desc.length > 3) desc = desc.slice(0, -2);
      draw(desc, { x: 48, y, size: 10, font, color: ink });
      if (it.quantity != null) draw(String(it.quantity), { x: width - 240, y, size: 10, font, color: ink });
      if (it.unit_price != null) {
        draw(fmtMoney(it.unit_price, data.currency || "DKK", lang), { x: width - 190, y, size: 10, font, color: ink });
      }
      const totalText = fmtMoney(it.total, data.currency || "DKK", lang);
      const tW = font.widthOfTextAtSize(sanitize(totalText), 10);
      draw(totalText, { x: width - 48 - tW, y, size: 10, font, color: ink });
      y -= 16;
    }
    y -= 8;
  }

  if (data.notes) {
    if (y < 140) y = 140;
    draw(t.notes, { x: 48, y, size: 9, font, color: muted });
    y -= 16;
    const words = sanitize(data.notes).split(/\s+/);
    let curLine = "";
    const maxW = width - 96;
    for (const w of words) {
      const test = curLine ? `${curLine} ${w}` : w;
      if (font.widthOfTextAtSize(test, 10) > maxW) {
        draw(curLine, { x: 48, y, size: 10, font, color: ink });
        y -= 14;
        curLine = w;
      } else curLine = test;
    }
    if (curLine) draw(curLine, { x: 48, y, size: 10, font, color: ink });
  }

  page.drawLine({ start: { x: 48, y: 80 }, end: { x: width - 48, y: 80 }, thickness: 1, color: line });
  draw(t.footer, { x: 48, y: 60, size: 9, font, color: muted });
  draw(new Date().toISOString().slice(0, 10), { x: 48, y: 46, size: 9, font, color: muted });

  return await doc.save();
}
